CREATE TABLE IF NOT EXISTS Customers(ID INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255), state VARCHAR(2));
CREATE TABLE IF NOT EXISTS Products(ID INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), price DOUBLE(11,2));
CREATE TABLE IF NOT EXISTS Orders(ID INT AUTO_INCREMENT PRIMARY KEY, created_at DATETIME, customer_id INT, product_id INT, FOREIGN KEY (customer_id) REFERENCES Customers(ID) ON DELETE CASCADE, FOREIGN KEY (product_id) REFERENCES Products(ID) ON DELETE CASCADE);


